export const ADD_SALE_ITEM = 'ADD_SALE_ITEM';
export const SHOW_DATE_WARNING = 'SHOW_DATE_WARNING';
export const HIDE_DATE_WARNING = 'HIDE_DATE_WARNING';
export const TOGGLE_INTERESTED_IN = 'TOGGLE_INTERESTED_IN';